apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: $VAR_PROJECT-teste
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 480730062915.dkr.ecr.us-west-1.amazonaws.com/nginx-teste-devops:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "1"
	command:
          - apt-get update
          - apt-get install stress-ng -y
          - stress-ng 
	  - --cpu 1 --vm 1 --hdd 1  --fork 1 --switch 1 --timeout 60 --metrics
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: myregistrykey

